#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : UCD
Version  : 1
Release  : 1
URL      : https://www.unicode.org/Public/zipped/12.1.0/UCD.zip
Source0  : https://www.unicode.org/Public/zipped/12.1.0/UCD.zip
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: UCD-data = %{version}-%{release}
Patch1: build.patch

%description
No detailed description available

%package data
Summary: data components for the UCD package.
Group: Data

%description data
data components for the UCD package.


%prep
%setup -q -n auxiliary
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1559114731
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1559114731
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/unicode/ucd/GraphemeBreakProperty.txt
/usr/share/unicode/ucd/GraphemeBreakTest.html
/usr/share/unicode/ucd/GraphemeBreakTest.txt
/usr/share/unicode/ucd/LineBreakTest.html
/usr/share/unicode/ucd/LineBreakTest.txt
/usr/share/unicode/ucd/Makefile
/usr/share/unicode/ucd/SentenceBreakProperty.txt
/usr/share/unicode/ucd/SentenceBreakTest.html
/usr/share/unicode/ucd/SentenceBreakTest.txt
/usr/share/unicode/ucd/WordBreakProperty.txt
/usr/share/unicode/ucd/WordBreakTest.html
/usr/share/unicode/ucd/WordBreakTest.txt
